"""config.py — Runtime configuration (reads live from Firebase + env vars)."""
import os
import firebase_helper as fb

FIREBASE_URL    = os.environ.get("FIREBASE_URL", "")
FIREBASE_SECRET = os.environ.get("FIREBASE_SECRET", "")
SECRET_KEY      = os.environ.get("SECRET_KEY", "predictor-secret-2026-change-me")
FLASK_PORT      = int(os.environ.get("PORT", 5000))

def BOT_TOKEN():      return (os.environ.get("BOT_TOKEN","") or fb.cfg("bot_token","")).strip()
def SUPPORT_BOT_TOKEN(): return (os.environ.get("SUPPORT_BOT_TOKEN","") or fb.cfg("support_bot_token","")).strip()
def BOT_USERNAME():   return fb.cfg("bot_username","PredictorBot")
def CHANNEL_ID():     return fb.cfg("channel_id","")
def CHANNEL_INVITE(): return fb.cfg("channel_invite","https://t.me/")
def ADMIN_CHAT_ID():  return str(fb.cfg("admin_chat_id",""))
def ADMIN_USERNAME():
    v = fb.cfg("admin_username","")
    return v if v else os.environ.get("ADMIN_USERNAME","admin")
def ADMIN_PASSWORD():
    v = fb.cfg("admin_password","")
    return v if v else os.environ.get("ADMIN_PASSWORD","Admin@2026")
def NOTIFY_CHAT_IDS():
    raw = fb.cfg("notify_chat_ids","")
    if not raw: return [ADMIN_CHAT_ID()] if ADMIN_CHAT_ID() else []
    return [x.strip() for x in str(raw).split(",") if x.strip()]
def SUPPORT_NOTIFY_CHAT_IDS():
    raw = fb.cfg("support_notify_chat_ids","")
    if raw: return [x.strip() for x in str(raw).split(",") if x.strip()]
    return NOTIFY_CHAT_IDS()
def SITE_URL():          return fb.cfg("site_url","http://localhost:5000")
def REFER_COMMISSION():  return float(fb.cfg("refer_commission",10))
def MIN_WITHDRAWAL():    return int(fb.cfg("min_withdrawal",100))
def MAX_WITHDRAWAL():    return int(fb.cfg("max_withdrawal",50000))
def SUPPORT_GREETING():  return fb.cfg("support_greeting","👋 *Welcome to Support!*\n\nPlease describe your issue.")
def PANEL_URL():         return fb.cfg("panel_url","")

def PRIVACY_POLICY():
    stored = fb.cfg("privacy_policy","")
    if stored: return stored
    return (
        "🔒 *Privacy Policy — Predictor 4.0*\n"
        "━━━━━━━━━━━━━━━━━━━━━\n\n"
        "📌 *Data We Collect*\n"
        "We collect your Telegram Chat ID, username, and full name to provide the service. "
        "Payment data is handled by KimiPay and never stored on our servers.\n\n"
        "🤖 *AI Predictions*\n"
        "This application uses Google Gemini AI to generate predictions based on historical game data. "
        "AI predictions are for entertainment purposes only. "
        "*There is NO 100% win guarantee.* Past results do not guarantee future outcomes.\n\n"
        "🎰 *Disclaimer*\n"
        "Predictor 4.0 is NOT affiliated with, endorsed by, or connected to any gambling website, "
        "lottery platform, or gaming company. We do not promote gambling. "
        "Use at your own discretion.\n\n"
        "🔐 *Data Security*\n"
        "Your data is stored securely. We never sell or share your data with third parties.\n\n"
        "📩 *Data Deletion*\n"
        "Contact support to request deletion of your data at any time.\n\n"
        "_Last updated: 2026_"
    )

def TERMS_CONDITIONS():
    stored = fb.cfg("terms_conditions","")
    if stored: return stored
    return (
        "📋 *Terms & Conditions — Predictor 4.0*\n"
        "━━━━━━━━━━━━━━━━━━━━━\n\n"
        "1️⃣ *License Keys*\n"
        "License keys are non-transferable and bound to your Telegram account. "
        "Each account may hold one active license at a time.\n\n"
        "2️⃣ *AI Predictions*\n"
        "All predictions are generated by AI and are for informational purposes only. "
        "There is NO guarantee of winning. We are not responsible for any financial losses.\n\n"
        "3️⃣ *No Affiliation*\n"
        "We are NOT affiliated with, endorsed by, or related to any gaming, lottery, "
        "or gambling website or application.\n\n"
        "4️⃣ *Prohibited Actions*\n"
        "Sharing, reselling, or misusing a license key will result in permanent account ban "
        "with no refund.\n\n"
        "5️⃣ *Refund Policy*\n"
        "Refunds are not offered after license key delivery.\n\n"
        "6️⃣ *Account Bans*\n"
        "We reserve the right to ban accounts that violate these terms without notice.\n\n"
        "7️⃣ *Referral Earnings*\n"
        "Referral commissions are credited to your wallet and subject to our withdrawal policy.\n\n"
        "By using this service you agree to all terms above.\n\n"
        "_Last updated: 2026_"
    )

LICENSE_PLANS = {
    "7day":   {"label": "7 Days",  "days": 7,  "amount": 2000},
    "15day":  {"label": "15 Days", "days": 15, "amount": 5000},
    "1month": {"label": "1 Month", "days": 30, "amount": 8000},
}
